### ISSUE TITLE
Occasional WorkerID mismatch?

### ISSUE THREAD

**Issue by ejolly** [VirtualLab/turkserver-meteor#67]
I'm running into the following issue when trying to approve a bunch of submitted assignments (or even refresh their states) from the admin interface. I have been successfully able to approve several assignments for this experiment, but now I seem to be stuck on this:
```
Exception while invoking method 'ts-admin-count-submitted' Error: Worker ID doesn't match
    at Assignment.refreshStatus (server/assignment.js:324:13)
    at packages/mizzao_turkserver/admin/admin.coffee:432:12
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
    at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:869:1)
    at [object Object].Meteor.methods.ts-admin-refresh-assignments (packages/mizzao_turkserver/admin/admin.coffee:429:8)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:1611:18
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.apply (livedata_server.js:1610:45)
    at [object Object]._.extend.call (livedata_server.js:1553:17)
```
Is there a way to figure out which assignment this is referring to? If I look at the first non-approved assignment in the admin interface everything seems to be in order, i.e the status is completed, mturkStatus is submitted and I can see the assignment on Amazon's requestor site. I'm not quite sure how to proceed here. I've tried changing both the status and mturkStatus (similar to the solution used in #56 ) just to see if I can at least approve the subsequent submitted assignments, but this isn't working as the admin interface still produces the same error.

**Comment by mizzao** [comment]
I've been on vacation but we can try to fix this in person this week.

**Comment by ejolly** [comment]
```
{ asstId: 'n4hJRgJzxWWmfLazM',
  batchId: 'XivpC8YSnRQ5Z6Rj7',
  hitId: '3EKZL9T8Y8GPVKF9CYX6VPN9YR2CH8',
  assignmentId: '3634BBTX0POYHB8XZKATSR5CHLBIFP',
  workerId: 'AKSJ3C5O3V9RN',
  userId: 'Fd4o595sJ9siFRGAJ' }
 { AssignmentId: '3634BBTX0POYHB8XZKATSR5CHLBIFP',
  WorkerId: 'AKSJ3C5O3V9RB',
  HITId: '3EKZL9T8Y8GPVKF9CYX6VPN9YR2CH8',
  AssignmentStatus: 'Approved',
  AutoApprovalTime: Sun May 29 2016 12:39:34 GMT-0400 (EDT),
  AcceptTime: Sat May 28 2016 12:06:55 GMT-0400 (EDT),
  SubmitTime: Sat May 28 2016 12:39:34 GMT-0400 (EDT),
  ApprovalTime: Sun May 29 2016 12:42:38 GMT-0400 (EDT),
  Answer: '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<QuestionFormAnswers xmlns="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionFormAnswers.xsd">\n<Answer>\n<QuestionIdentifier>workerId</QuestionIdentifier>\n<FreeText>AKSJ3C5O3V9RN</FreeText>\n</Answer>\n</QuestionFormAnswers>' }
```

**Comment by mizzao** [comment]
Seems like a few bits were flipped on the workerId. No idea why this happened, but it doesn't seem like a common error. We fixed it by just twiddling the database, but will keep this in mind for future problems.
